project_name: fluent-bit-go-pulsar-output
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: pulsar-go-linux
    main: .
    binary: out_pulsar.so
    flags:
      - -buildmode=c-shared
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - dist/CHANGELOG.md
      - dist/pulsar-go-linux_linux_amd64/out_pulsar.h
release:
  prerelease: auto
