version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar:2.10.3
    expose:
      - 8080
      - 6650
      - 8843
      - 6651
    ports:
      - "8080:8080"
      - "6650:6650"
      - "8843:8843"
      - "6651:6651"
    command: bin/pulsar standalone --no-functions-worker --no-stream-storage

  fluentbit:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pulsar
    volumes:
      - ./sp-samples-1k.log:/fluent-bit/etc/sp-samples-1k.log
