version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar:2.6.0
    expose:
      - 8080
      - 6650
    command: bin/pulsar standalone

  fluentbit:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pulsar
