version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar
    expose:
      - 8080
      - 6650
    environment:
      - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"

  fluentbit:
    build:
      context: .
      dockerfile: Dockerfile
    configs:
      - source: fluentbit_config
        target: /fluent-bit/etc/fluent-bit.conf

configs:
  fluentbit_config:
    file: ./example/fluent.conf
