name: Vulnerability Scan
# schedule on sunday at 0:00(UTC) = 9:00(JST)
on:
  schedule:
    - cron: '0 0 * * 6'
jobs:
  scan:
    name: Weekly Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull ${{ github.repository }}:latest

      - uses: homoluctus/gitrivy@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ github.repository }}
          issue_assignee: transnano
